ARG SDCC_VERSION=4.3.0
ARG SDCC_ROOT=/opt/sdcc

ARG GBDK_2020_VERSION=4.2.0
ARG GBDK_2020_ROOT=/opt/gbdk

FROM alpine:latest AS build

ARG SDCC_VERSION
ARG SDCC_ROOT

ARG GBDK_2020_VERSION
ARG GBDK_2020_ROOT

RUN apk add --update --no-cache \
    bison boost-dev flex g++ make musl-dev patch texinfo wget zlib-static

WORKDIR /usr/src

RUN wget https://sourceforge.net/projects/sdcc/files/sdcc/${SDCC_VERSION}/sdcc-src-${SDCC_VERSION}.tar.bz2 \
  && wget https://github.com/gbdk-2020/gbdk-2020-sdcc/releases/download/patches/gbdk-4.2-nes_banked_nonbanked_v4_combined.diff.patch \
  && tar xf sdcc-src-${SDCC_VERSION}.tar.bz2 \
  && cd sdcc-${SDCC_VERSION} \
  && patch -p0 < ../gbdk-4.2-nes_banked_nonbanked_v4_combined.diff.patch \
  && mkdir build \
  && cd build \
  && LDFLAGS="-static" ../configure \
    --prefix=$SDCC_ROOT \
    --build=x86_64-pc-linux \
    --disable-shared \
    --disable-mcs51-port \
    --enable-z80-port \
    --disable-z180-port \
    --disable-r2k-port \
    --disable-r2ka-port \
    --disable-r3ka-port \
    --enable-sm83-port \
    --disable-tlcs90-port \
    --disable-ez80_z80-port \
    --disable-z80n-port \
    --disable-ds390-port \
    --disable-ds400-port \
    --disable-pic14-port \
    --disable-pic16-port \
    --disable-hc08-port \
    --disable-s08-port \
    --disable-stm8-port \
    --disable-pdk13-port \
    --disable-pdk14-port \
    --disable-pdk15-port \
    --disable-pdk16-port \
    --enable-mos6502-port \
    --disable-mos65c02-port \
    --disable-ucsim \
    --disable-device-lib \
    --disable-doc \
  && make \
  && make install \
  && find $SDCC_ROOT/bin -type f ! -name as2gbmap -perm /a=x -exec strip {} \;

RUN wget https://github.com/gbdk-2020/gbdk-2020/archive/refs/tags/${GBDK_2020_VERSION}.tar.gz -O gbdk-2020-${GBDK_2020_VERSION}.tar.gz \
  && tar xf gbdk-2020-${GBDK_2020_VERSION}.tar.gz \
  && cd gbdk-2020-${GBDK_2020_VERSION} \
  && make SDCCDIR=$SDCC_ROOT TARGETDIR=$GBDK_2020_ROOT \
  && make SDCCDIR=$SDCC_ROOT TARGETDIR=$GBDK_2020_ROOT install \
  && find $GBDK_2020_ROOT/bin -type f -perm /a=x -exec strip {} \;

FROM alpine:latest

ARG GBDK_2020_ROOT

RUN apk add --update --no-cache make

COPY --from=build $GBDK_2020_ROOT $GBDK_2020_ROOT

ENV PATH $GBDK_2020_ROOT/bin:$PATH
WORKDIR /workdir
